[package]
name = "lorsrf"
authors = "Khaled Nassar <knassar702@gmail.com>"
repository = "https://github.com/knassar702/lorsrf"
license = "GPLv3"
version = "2.0.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isahc = "1.5.1"
serde_json = "1.0.69"
clap = "2.33.0"
url = "2.2.2"
scoped_threadpool = "0.1.9"