on:
  release:
    types: [created]

jobs:
  release:
    name: release ${{ matrix.target }}  (with non-required env)
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-unknown-freebsd
            archive: zip
          - target: x86_64-unknown-linux-gnu
            archive: zip
          - target: x86_64-unknown-linux-gnux32
            archive: zip
          - target: i686-unknown-freebsd
            archive: zip
          - target: x86_64-unknown-openbsd
            archive: zip
          - target: i686-unknown-openbsd
            archive: zip
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUSTTARGET: ${{ matrix.target }}
          SRC_DIR: "."
          ARCHIVE_TYPES: ${{ matrix.archive }}
  release_without_not_required:
    name: release ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        target: [x86_64-unknown-linux-musl]
    steps:
      - uses: actions/checkout@master
      - name: Compile and release
        uses: rust-build/rust-build.action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT }}
          RUSTTARGET: ${{ matrix.target }}
